main: it.mikeslab.Main
version: ${project.version}
name: ${project.name}
api-version: 1.16
author: MikesLab
description: Bank plug-in for Minecraft
website: mikeslab.it
softdepend:
  - Vault
  - PlaceholderAPI